name: continuous-integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.7.0
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run unit tests
        run: npm test 
